import { userEndpoints } from '../endpoints';

const newReportForms = {
  firstSection: [
    {
      control: 'input',
      label: 'Numer',
      name: 'nr',
      type: 'number',
      placeholder: '0',
    },
    {
      control: 'select',
      label: 'Inżynier',
      name: 'workers[0]',
      shouldFetchOptions: true,
      options: [],
      refKey: 'fullName',
      refEndpoint: userEndpoints.get,
      defaultOptionLabel: 'Wybierz inżyniera',
      placeholder: 'Imię i nazwisko inżyniera',
    },
    {
      control: 'select',
      label: 'Technik',
      name: 'workers[1]',
      shouldFetchOptions: true,
      options: [],
      refKey: 'fullName',
      refEndpoint: userEndpoints.get,
      defaultOptionLabel: 'Wybierz technika',
      placeholder: 'Imię i nazwisko technika',
    },
  ],
  secondSection: [
    {
      control: 'select',
      label: 'konfiguracja',
      name: 'configuration',
      placeholder: '',
      shouldFetchOptions: false,
      options: [
        {
          text: '1+2',
          value: '1+2',
        },
        {
          text: '2+3',
          value: '2+3',
        },
        {
          text: '1+3',
          value: '1+3',
        },
        {
          text: '1+2+3',
          value: '1+2+3',
        },
      ],
      defaultOptionLabel: 'Wybierz konfigurację',
    },
    {
      control: 'input',
      label: 'pwr_set',
      name: 'pwr_set',
      type: 'number',
      placeholder: '0',
    },
    {
      control: 'input',
      label: 'mod_set',
      name: 'mod_set',
      type: 'number',
      placeholder: '0',
    },
    {
      control: 'input',
      label: 'moduł',
      name: 'module',
      type: 'text',
      placeholder: 'ABB4',
    },
    {
      control: 'select',
      label: 'rms',
      name: 'rms',
      shouldFetchOptions: false,
      options: [
        {
          text: 'ZAŁ',
          value: 'ZAL',
        },
        {
          text: 'WYŁ',
          value: 'WYL',
        },
      ],
      defaultOptionLabel: 'Wybierz RMS',
    },
    {
      control: 'select',
      label: 'Pompa',
      name: 'pump',
      shouldFetchOptions: false,
      options: [
        {
          text: 'P1',
          value: 'P1',
        },
        {
          text: 'P2',
          value: 'P2',
        },
      ],
      defaultOptionLabel: 'Wybierz pompę',
    },
    {
      control: 'input',
      label: 'Ciśnienie',
      name: 'pressure',
      type: 'number',
      placeholder: '0',
    },
    {
      control: 'input',
      label: 'Temperatura wejściowa',
      name: 'temperatureIn',
      type: 'number',
      placeholder: '0',
    },
    {
      control: 'input',
      label: 'Temperatura wyjściowa',
      name: 'temperatureOut',
      type: 'number',
      placeholder: '0',
    },
    {
      control: 'input',
      label: 'Rezystancja wejściowa układu chłodzenia',
      name: 'resistanceIn',
      type: 'number',
      placeholder: '0',
    },
    {
      control: 'input',
      label: 'Rezystancja wyjściowa układu chłodzenia',
      name: 'resistanceOut',
      type: 'number',
      placeholder: '0',
    },
    {
      control: 'input',
      label: 'Licznik wody',
      name: 'waterCounter',
      type: 'number',
      placeholder: '0',
    },
    {
      control: 'input',
      label: 'Stopień otwarcia żaluzji A',
      name: 'openingLevelA',
      type: 'number',
      placeholder: '0',
    },
    {
      control: 'input',
      label: 'Stopień otwarcia żaluzji B',
      name: 'openingLevelB',
      type: 'number',
      placeholder: '0',
    },
    {
      control: 'input',
      label: 'Ilość zapasu',
      name: 'supplyAmount',
      type: 'number',
      placeholder: '0',
    },
    {
      control: 'checkbox',
      label: 'Oświetlenie przeszkodowe',
      name: 'lighting',
      type: 'checkbox',
      placeholder: '',
    },
    {
      control: 'checkbox',
      label: 'Kaseta',
      name: 'isCassetteOpened',
      type: 'checkbox',
      placeholder: '',
    },
    {
      control: 'select',
      label: 'dab_exciter',
      name: 'dabExciter',
      shouldFetchOptions: false,
      options: [
        {
          text: 'A',
          value: 'A',
        },
        {
          text: 'B',
          value: 'B',
        },
      ],
      defaultOptionLabel: 'Wybierz moduł',
    },
    {
      control: 'input',
      label: 'dab_moc_wyj',
      name: 'dabPowerOut',
      type: 'number',
      placeholder: '0',
    },
    {
      control: 'input',
      label: 'dab_moc_odb',
      name: 'dabPowerReceived',
      type: 'number',
      placeholder: '0',
    },
    {
      control: 'input',
      label: 'dab_mer',
      name: 'dabMer',
      type: 'number',
      placeholder: '0',
    },
    {
      control: 'input',
      label: 'dab_shoulder_up',
      name: 'dabShoulderUp',
      type: 'number',
      placeholder: '0',
    },
    {
      control: 'input',
      label: 'dab_shoulder_down',
      name: 'dabShoulderDown',
      type: 'number',
      placeholder: '0',
    },
    {
      control: 'input',
      label: 'dab_t_ogolna',
      name: 'dabGeneral',
      type: 'number',
      placeholder: '0',
    },
    {
      control: 'input',
      label: 'dab_t_ma',
      name: 'dabTMA',
      type: 'number',
      placeholder: '0',
    },
    {
      control: 'input',
      label: 'dab_t_mb',
      name: 'dabTMB',
      type: 'number',
      placeholder: '0',
    },
    {
      control: 'textarea',
      label: 'zdarzenie',
      name: 'accidentDescription',
      type: 'text',
      placeholder: 'Opis',
    },
  ],
};

export default newReportForms;
